version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: mix
    environment:
      - PORT=${PORT}
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=benarid
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "${PORT}:4000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=benarid
    ports:
      - "${DB_PORT}:5432"
