version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: mix
    environment:
      - MIX_ENV=dev
      - API_PORT=${API_PORT}
      - AUTH_PROVIDER_PORT=${AUTH_PROVIDER_PORT}
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=benarid
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "${API_PORT}:4000"
      - "${AUTH_PROVIDER_PORT}:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=benarid
    ports:
      - "${DB_PORT}:5432"
