use Mix.Config

# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :benarid, BenarID.Endpoint,
  url: [host: System.get_env("HOST"), port: 80],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Do not print debug messages in production
config :logger, level: :info

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
# config :phoenix, :serve_endpoints, true

# Configure production database
config :benarid, BenarID.Repo,
  ssl: true,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "20")

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"
